# Generated by Django 5.1.6 on 2025-03-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('atomic_weight', models.FloatField()),
                ('density', models.FloatField()),
                ('electronegativity', models.FloatField()),
                ('oxidation_states', models.JSONField()),
                ('melting_point', models.FloatField()),
                ('boiling_point', models.FloatField()),
                ('heat_capacity', models.FloatField()),
                ('latent_heat_fusion', models.FloatField()),
                ('latent_heat_vaporization', models.FloatField()),
            ],
        ),
    ]
