# Generated by Django 5.1.6 on 2025-04-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_radius', models.FloatField(default=9.0)),
                ('cell_height', models.FloatField(default=65.0)),
                ('thermal_conductivity', models.FloatField(default=30.0)),
                ('specific_heat_capacity', models.FloatField(default=900.0)),
                ('density', models.FloatField(default=2700.0)),
                ('initial_temperature', models.FloatField(default=25.0)),
                ('ambient_temperature', models.FloatField(default=25.0)),
                ('nominal_capacity', models.FloatField(default=3000.0)),
                ('nominal_voltage', models.FloatField(default=3.7)),
                ('internal_resistance', models.FloatField(default=0.02)),
                ('time_step', models.FloatField(default=1.0)),
                ('max_simulation_time', models.FloatField(default=3600.0)),
                ('current_profile', models.TextField(default='{"0": 1.0, "1800": 2.0, "3600": 0.5}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MaterialProperty',
        ),
    ]
