# Generated by Django 5.1.6 on 2025-04-14 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core1', '0002_simulationparameters_delete_materialproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_type', models.CharField(choices=[('li_ion_phosphate', 'Li-ion Phosphate'), ('li_ion_cobalt', 'Li-ion Cobalt'), ('nimh', 'NiMH'), ('lead_acid', 'Lead Acid')], max_length=50)),
                ('form_factor', models.CharField(choices=[('cylindrical', 'Cylindrical'), ('prismatic', 'Prismatic'), ('pouch', 'Pouch')], max_length=20)),
                ('length', models.FloatField(help_text='Length in mm')),
                ('diameter', models.FloatField(blank=True, help_text='Diameter in mm', null=True)),
                ('height', models.FloatField(blank=True, help_text='Height in mm', null=True)),
                ('width', models.FloatField(blank=True, help_text='Width in mm', null=True)),
                ('volume', models.FloatField(blank=True, help_text='Volume in cm³', null=True)),
                ('nominal_voltage', models.FloatField(help_text='Nominal voltage in V')),
                ('capacity', models.FloatField(help_text='Capacity in mAh')),
                ('energy_density', models.FloatField(help_text='Energy density in Wh/kg')),
                ('internal_resistance', models.FloatField(help_text='Internal resistance in mΩ')),
                ('heat_resistance', models.FloatField(help_text='Thermal resistance in K/W')),
                ('max_discharge_current', models.FloatField(help_text='Maximum discharge current in A')),
                ('max_charge_current', models.FloatField(help_text='Maximum charge current in A')),
                ('cycle_life', models.IntegerField(help_text='Expected cycle life')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('load_resistance', models.FloatField(help_text='Load resistance in Ω')),
                ('initial_soc', models.FloatField(help_text='Initial state of charge (0-100%)')),
                ('temperature', models.FloatField(help_text='Ambient temperature in °C')),
                ('simulation_duration', models.IntegerField(help_text='Simulation duration in minutes')),
                ('emf_data', models.JSONField(null=True)),
                ('terminal_voltage_data', models.JSONField(null=True)),
                ('current_data', models.JSONField(null=True)),
                ('resistance_data', models.JSONField(null=True)),
                ('soc_data', models.JSONField(null=True)),
                ('temperature_data', models.JSONField(null=True)),
                ('battery_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core1.batterycell')),
            ],
        ),
        migrations.DeleteModel(
            name='SimulationParameters',
        ),
    ]
