# Generated by Django 5.1.6 on 2025-04-15 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core1', '0003_batterycell_simulationresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicLoadPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_point', models.FloatField(help_text='Time point in minutes when load changes')),
                ('load_resistance', models.FloatField(help_text='New load resistance in Ω')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_loads', to='core1.simulationresult')),
            ],
            options={
                'ordering': ['time_point'],
            },
        ),
    ]
