# Generated by Django 5.1.6 on 2025-04-15 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core1', '0004_dynamicloadpoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DynamicLoadPoint',
        ),
    ]
